version: '3'
services:
  mongodb-dev:
    container_name: mongodb-dev
    image: "mongo:latest"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=app
    ports:
      - "50030:27017"

volumes:
  mongodb:
    driver: local